In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

In [2]:
df = pd.read_csv('spam.csv')

In [3]:
df.head(5)

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [5]:
df.Category.value_counts()/len(df)*100

Category
ham     86.593683
spam    13.406317
Name: count, dtype: float64

In [6]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [7]:
df.head(5)

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [8]:
new_df = pd.read_csv('spam.csv')

In [9]:
new_df['Category'].replace({'ham':0,'spam':1}, inplace=True)

C:\Users\Dell\AppData\Local\Temp\ipykernel_1560\2701969205.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  new_df['Category'].replace({'ham':0,'spam':1}, inplace=True)
C:\Users\Dell\AppData\Local\Temp\ipykernel_1560\2701969205.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  new_df['Category'].replace({'ham':0,'spam':1}, inplace=True)

In [10]:
new_df.head(5)

   Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

In [11]:
df.head(5)

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [12]:
df.shape

(5572, 3)

#### **Train Test Split**

In [13]:
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam,test_size=0.2)

In [14]:
X_train.shape

(4457,)

In [15]:
X_test.shape

(1115,)

In [16]:
X_train[:4]

3632               Thank you princess! You are so sexy...
4516    That was random saw my old roomate on campus. ...
5342    u r subscribed 2 TEXTCOMP 250 wkly comp. 1st w...
850     Today's Offer! Claim ur £150 worth of discount...
Name: Message, dtype: object

In [17]:
y_train[:4]

3632    0
4516    0
5342    1
850     1
Name: spam, dtype: int64

#### **Create bag of words representation using CountVectorizer**

In [18]:
v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_test_cv = v.transform(X_test)

In [19]:
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59030 stored elements and shape (4457, 7679)>

In [20]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7679,))

In [21]:
X_train_cv.shape

(4457, 7679)

In [22]:
v.get_feature_names_out()[1771]

'ciao'

In [23]:
v.vocabulary_

{'thank': 6728,
 'you': 7636,
 'princess': 5339,
 'are': 1027,
 'so': 6210,
 'sexy': 5971,
 'that': 6737,
 'was': 7313,
 'random': 5498,
 'saw': 5850,
 'my': 4588,
 'old': 4851,
 'roomate': 5744,
 'on': 4857,
 'campus': 1589,
 'he': 3304,
 'graduated': 3167,
 'subscribed': 6492,
 'textcomp': 6717,
 '250': 354,
 'wkly': 7489,
 'comp': 1878,
 '1st': 320,
 'wk': 7486,
 'free': 2935,
 'question': 5458,
 'follows': 2873,
 'subsequent': 6497,
 'wks': 7491,
 'charged': 1694,
 '150p': 288,
 'msg': 4537,
 'unsubscribe': 7105,
 'txt': 7017,
 'stop': 6424,
 '84128': 659,
 'custcare': 2080,
 '08712405020': 101,
 'today': 6864,
 'offer': 4824,
 'claim': 1778,
 'ur': 7126,
 '150': 286,
 'worth': 7537,
 'of': 4820,
 'discount': 2295,
 'vouchers': 7250,
 'text': 6713,
 'yes': 7620,
 'to': 6859,
 '85023': 663,
 'now': 4765,
 'savamob': 5845,
 'member': 4366,
 'offers': 4827,
 'mobile': 4469,
 'cs': 2046,
 '08717898035': 125,
 '00': 0,
 'sub': 6485,
 '16': 300,
 'unsub': 7104,
 'reply': 5643,
 'come': 1863,
 'round': 5752,
 'it': 3686,
 'ic': 3518,
 'there': 6760,
 'lotta': 4145,
 'childporn': 1741,
 'cars': 1631,
 'then': 6755,
 'todays': 6865,
 'vodafone': 7238,
 'numbers': 4781,
 'ending': 2540,
 'with': 7477,
 '4882': 493,
 'selected': 5924,
 'receive': 5558,
 '350': 432,
 'award': 1148,
 'if': 3536,
 'your': 7642,
 'number': 4780,
 'matches': 4309,
 'call': 1568,
 '09064019014': 203,
 'sorry': 6260,
 'sir': 6115,
 'will': 7447,
 'tomorrow': 6885,
 'senthil': 5948,
 'hsbc': 3469,
 'probably': 5355,
 'couple': 1994,
 'hours': 3452,
 'tops': 6909,
 'certainly': 1673,
 'puts': 5440,
 'things': 6773,
 'into': 3648,
 'perspective': 5096,
 'when': 7406,
 'something': 6235,
 'like': 4037,
 'this': 6782,
 'happens': 3270,
 'doing': 2343,
 'masters': 4305,
 'buy': 1542,
 'bb': 1229,
 'cos': 1975,
 'have': 3295,
 'for': 2888,
 'sale': 5809,
 'and': 940,
 'how': 3457,
 'bf': 1309,
 'kate': 3825,
 'jackson': 3708,
 'rec': 5554,
 'center': 1668,
 'before': 1269,
 '7ish': 612,
 'right': 5705,
 'thanx': 6734,
 'in': 3577,
 'cbe': 1652,
 'chennai': 1724,
 'get': 3070,
 'the': 6741,
 'door': 2361,
 'here': 3350,
 'miss': 4435,
 'much': 4553,
 'desparate': 2216,
 'recorded': 5572,
 'message': 4385,
 'left': 3990,
 'me': 4335,
 'other': 4924,
 'day': 2136,
 'listen': 4067,
 'just': 3801,
 'hear': 3315,
 'sound': 6269,
 'voice': 7240,
 'love': 4154,
 'havent': 3298,
 'mus': 4574,
 'ask': 1074,
 'can': 1591,
 'wat': 7318,
 'meet': 4353,
 'lunch': 4188,
 'den': 2191,
 'him': 3372,
 'already': 902,
 'lor': 4133,
 'or': 4896,
 'wan': 7295,
 'go': 3113,
 'da': 2097,
 'ge': 3050,
 'confirm': 1914,
 'asap': 1067,
 'meeting': 4355,
 'll': 4085,
 'later': 3952,
 'no': 4716,
 'didn': 2254,
 'spring': 6343,
 'is': 3674,
 'coming': 1869,
 'early': 2453,
 'yay': 7607,
 'am': 914,
 'pa': 4967,
 'oh': 4836,
 'ya': 7596,
 'remember': 5616,
 'by': 1553,
 'way': 7334,
 'do': 2320,
 'more': 4509,
 'food': 2880,
 'fridge': 2953,
 'want': 7300,
 'out': 4934,
 'meal': 4336,
 'tonight': 6893,
 'detroit': 2228,
 'home': 3413,
 'snow': 6206,
 'enjoy': 2554,
 'over': 4949,
 'scratching': 5879,
 'thinl': 6780,
 'role': 5737,
 'sachin': 5793,
 'standing': 6369,
 'others': 4925,
 'hit': 3381,
 'don': 2351,
 'her': 3349,
 'hows': 3462,
 'favourite': 2742,
 'person': 5090,
 'workin': 7525,
 'hard': 3275,
 'couldn': 1987,
 'sleep': 6147,
 'again': 836,
 'last': 3949,
 'nite': 4709,
 'nearly': 4642,
 'rang': 5502,
 'at': 1097,
 '30': 412,
 'slave': 6146,
 'going': 3123,
 'shell': 6004,
 'unconsciously': 7065,
 'avoiding': 1143,
 'making': 4259,
 'unhappy': 7081,
 'ok': 4840,
 'finish': 2805,
 'pick': 5127,
 'sometimes': 6237,
 'we': 7339,
 'put': 5439,
 'walls': 7291,
 'around': 1050,
 'our': 4931,
 'hearts': 3321,
 'not': 4753,
 'be': 1243,
 'safe': 5800,
 'from': 2972,
 'getting': 3078,
 'hurt': 3495,
 'but': 1538,
 'find': 2801,
 'who': 7422,
 'cares': 1621,
 'enough': 2560,
 'break': 1454,
 'amp': 928,
 'closer': 1807,
 'goodnoon': 3142,
 'should': 6049,
 'make': 4255,
 'fb': 2743,
 'list': 4065,
 'dump': 2436,
 'heap': 3314,
 'mom': 4487,
 'decided': 2158,
 'lowes': 4168,
 'boring': 1405,
 'nope': 4739,
 'juz': 3806,
 'off': 4821,
 'work': 7522,
 'dude': 2431,
 'sux': 6568,
 'snake': 6198,
 'got': 3151,
 'raiden': 5481,
 'buff': 1511,
 'darren': 2122,
 'oso': 4922,
 'sian': 6076,
 'tmr': 6854,
 'haf': 3239,
 'lect': 3987,
 'pls': 5185,
 'quick': 5461,
 'cant': 1602,
 'bare': 1206,
 'link': 4056,
 'picture': 5133,
 'has': 3283,
 'been': 1263,
 'sent': 5946,
 'also': 905,
 'use': 7145,
 'http': 3470,
 'alto18': 909,
 'co': 1827,
 'uk': 7046,
 'wave': 7332,
 'asp': 1082,
 '44345': 479,
 'fuck': 2981,
 'sake': 5805,
 'she': 5999,
 'tallahassee': 6629,
 'thanks': 6729,
 'picking': 5129,
 'up': 7109,
 'trash': 6947,
 'anything': 982,
 'specific': 6296,
 'regards': 5598,
 'jaklin': 3710,
 'what': 7399,
 'because': 1251,
 'idk': 3533,
 'give': 3098,
 'one': 4861,
 'please': 5177,
 'urgent': 7130,
 'awarded': 1149,
 '500': 521,
 'bonus': 1391,
 'caller': 1575,
 'prize': 5350,
 '27': 361,
 '03': 13,
 'final': 2797,
 'attempt': 1108,
 'contact': 1936,
 '08714714011': 111,
 'aight': 856,
 'back': 1173,
 'er': 2583,
 'yep': 7618,
 'sure': 6556,
 'props': 5393,
 'did': 2253,
 'ah': 849,
 'once': 4859,
 're': 5521,
 'close': 1804,
 'house': 3453,
 'water': 7325,
 'dock': 2324,
 'boat': 1380,
 'rolled': 5739,
 'newscaster': 4683,
 'dabbles': 2099,
 'jazz': 3730,
 'flute': 2860,
 'behind': 1277,
 'wheel': 7404,
 '10': 243,
 'min': 4412,
 'hhahhaahahah': 3361,
 'rofl': 5735,
 'wtf': 7562,
 'nig': 4695,
 'leonardo': 4004,
 'room': 5743,
 'watching': 7323,
 'tv': 7007,
 'new': 4678,
 'job': 3759,
 'haha': 3240,
 'money': 4494,
 'leh': 3996,
 'tuition': 6997,
 'looking': 4126,
 'empty': 2535,
 'slots': 6164,
 'driving': 2408,
 'lessons': 4009,
 'daddy': 2101,
 'shu': 6069,
 'tell': 6679,
 'singapore': 6107,
 'yup': 7661,
 'thk': 6783,
 'cine': 1772,
 'better': 1302,
 'need': 4649,
 'down': 2376,
 'plaza': 5175,
 'mah': 4242,
 'nokia': 4726,
 '3510i': 433,
 'colour': 1856,
 'phone': 5116,
 'deliveredtomorrow': 2186,
 '300': 413,
 'minutes': 4427,
 'any': 973,
 '100': 244,
 'texts': 6723,
 'camcorder': 1585,
 '08000930705': 46,
 'alright': 903,
 'took': 6899,
 'morphine': 4515,
 'yo': 7631,
 'thought': 6793,
 'could': 1985,
 'dinner': 2275,
 'treat': 6955,
 'seem': 5915,
 'tease': 6667,
 'cry': 2044,
 'end': 2538,
 'life': 4026,
 'die': 2257,
 'plz': 5190,
 'keep': 3833,
 'rose': 5749,
 'grave': 3180,
 'say': 5851,
 'stupid': 6480,
 'nice': 4690,
 'bslvyl': 1499,
 'win': 7450,
 'winner': 7461,
 'mr': 4532,
 'foley': 2867,
 'won': 7506,
 'an': 935,
 'ipod': 3666,
 'exciting': 2647,
 'prizes': 5351,
 'soon': 6251,
 'eye': 2685,
 'visit': 7228,
 'www': 7569,
 '82050': 638,
 'msgs': 4542,
 '80488': 630,
 'credit': 2022,
 'account': 765,
 'nervous': 4662,
 'lt': 4176,
 'gt': 3209,
 'bought': 1415,
 'test': 6707,
 'yesterday': 7622,
 'its': 3692,
 'lets': 4011,
 'know': 3885,
 'exact': 2640,
 'ovulate': 4955,
 '2u': 404,
 'about': 740,
 '3wks': 460,
 'dont': 2355,
 'fret': 2949,
 'worried': 7532,
 'relax': 5608,
 'past': 5028,
 'history': 3380,
 'wun': 7568,
 'believe': 1280,
 'really': 5540,
 'neva': 4673,
 'shuhui': 6072,
 'di': 2242,
 'times': 6830,
 'umma': 7052,
 'them': 6751,
 'speed': 6300,
 'hmv': 3396,
 'special': 6292,
 'pounds': 5270,
 'genuine': 3064,
 'answer': 962,
 'easy': 2464,
 'questions': 5460,
 'play': 5169,
 'send': 5938,
 '86688': 670,
 'info': 3609,
 '100percent': 249,
 'real': 5532,
 'com': 1859,
 'search': 5892,
 'let': 4010,
 'thats': 6740,
 'why': 7430,
 'called': 1574,
 'falling': 2711,
 'bcoz': 1238,
 'force': 2889,
 'yourself': 7647,
 'fall': 2710,
 'smeone': 6179,
 'hold': 3404,
 'gonna': 3132,
 'talk': 6623,
 'stuff': 6475,
 'anymore': 976,
 've': 7186,
 'cried': 2032,
 'themob': 6754,
 'comes': 1865,
 'selection': 5925,
 'hot': 3446,
 'downloads': 2379,
 'members': 4367,
 'click': 1799,
 'open': 4878,
 'next': 4686,
 'fone': 2876,
 'pen': 5063,
 'thing': 6772,
 'beyond': 1308,
 'joke': 3770,
 'wont': 7512,
 'biro': 1331,
 'as': 1065,
 'ever': 2619,
 'take': 6616,
 'care': 1614,
 'understand': 7071,
 'said': 5804,
 'look': 4122,
 'pretty': 5327,
 'wif': 7437,
 'long': 4118,
 'hair': 3243,
 'cutting': 2090,
 'quite': 5465,
 'short': 6040,
 'wine': 7457,
 'flowing': 2856,
 'nevering': 4676,
 'hey': 3358,
 'leave': 3984,
 'big': 1316,
 'deal': 2145,
 'studying': 6473,
 'sch': 5863,
 'anyway': 985,
 'night': 4698,
 'ended': 2539,
 'another': 959,
 'morning': 4513,
 'may': 4327,
 'smile': 6181,
 'sunny': 6535,
 'rays': 5514,
 'leaves': 3985,
 'worries': 7533,
 'blue': 1374,
 'bay': 1228,
 'gud': 3215,
 'mrng': 4534,
 'bout': 1417,
 '30ish': 418,
 'time': 6829,
 'bit': 1336,
 'ex': 2639,
 'eat': 2465,
 'smth': 6196,
 'else': 2518,
 'feel': 2750,
 'guilty': 3223,
 'good': 3134,
 'billy': 1323,
 'mates': 4311,
 'all': 890,
 'gone': 3130,
 'jogging': 3765,
 'concert': 1907,
 'chic': 1734,
 'common': 1875,
 'declare': 2165,
 'haven': 3297,
 'forgotten': 2900,
 'might': 4402,
 'bucks': 1505,
 'too': 6898,
 'searching': 5893,
 'words': 7521,
 'breather': 1460,
 'promise': 5379,
 'help': 3337,
 'granted': 3177,
 'fulfil': 2990,
 'wonderful': 7509,
 'blessing': 1356,
 'babe': 1165,
 'goes': 3120,
 'where': 7410,
 'sip': 6112,
 'cappuccino': 1606,
 'think': 6774,
 'kiss': 3873,
 'across': 773,
 'sea': 5891,
 '2nd': 393,
 'tried': 6963,
 '750': 603,
 'pound': 5268,
 '087187272008': 134,
 'now1': 4766,
 'only': 4867,
 '10p': 253,
 'per': 5071,
 'minute': 4426,
 'bt': 1501,
 'national': 4629,
 'rate': 5506,
 'serious': 5953,
 'base': 1213,
 'someone': 6229,
 'conacted': 1902,
 'dating': 2131,
 'service': 5955,
 'entered': 2563,
 'they': 6768,
 'fancy': 2720,
 'landline': 3929,
 '09111030116': 239,
 'pobox12n146tf15': 5197,
 'week': 7361,
 'no1': 4717,
 'tone': 6887,
 'mob': 4467,
 'every': 2620,
 '8007': 623,
 'txting': 7022,
 'getzed': 3079,
 'pobox': 5195,
 '36504': 436,
 'w45wq': 7263,
 'norm150p': 4744,
 'great': 3186,
 'hope': 3429,
 'man': 4265,
 'well': 7377,
 'endowed': 2543,
 'inches': 3581,
 'fantastic': 2723,
 'chance': 1682,
 'bigger': 1317,
 'lift': 4031,
 'losing': 4138,
 'live': 4077,
 'would': 7542,
 'first': 2818,
 'auntie': 1124,
 'huai': 3471,
 'juan': 3788,
 'never': 4675,
 'im': 3551,
 'wasn': 7315,
 'fault': 2736,
 'spouse': 6339,
 'pmt': 5192,
 'sumthin': 6530,
 '4give': 502,
 'shldxxxx': 6030,
 'possible': 5254,
 'teach': 6658,
 'congratulations': 1922,
 'either': 2503,
 'cd': 1656,
 'gift': 3085,
 'entry': 2572,
 'weekly': 7365,
 'draw': 2391,
 'music': 4577,
 '87066': 673,
 'tncs': 6858,
 'ldew': 3972,
 'win150ppmx3age16': 7451,
 'ditto': 2308,
 'worry': 7534,
 'saying': 5854,
 'whatever': 7400,
 'same': 5819,
 'peace': 5054,
 'looks': 4127,
 'wil': 7443,
 'headstart': 3311,
 'leaving': 3986,
 'desperate': 2218,
 'company': 1881,
 'head': 3305,
 'earlier': 2451,
 'were': 7386,
 'goin': 3121,
 'rummer': 5776,
 'note': 4754,
 'anyone': 977,
 'calling': 1580,
 'asks': 1079,
 'type': 7030,
 'disconnect': 2293,
 'coz': 2002,
 'iz': 3702,
 'terrorist': 6703,
 'sim': 6096,
 'card': 1610,
 'itz': 3696,
 'confirmd': 1915,
 'motorola': 4521,
 'verified': 7194,
 'cnn': 1825,
 'ibn': 3516,
 'guess': 3219,
 'somebody': 6227,
 'secretly': 5902,
 'fancies': 2719,
 'wanna': 7298,
 'us': 7141,
 '09065394973': 210,
 'datebox1282essexcm61xn': 2129,
 '18': 305,
 'excellent': 2644,
 'spent': 6308,
 'years': 7611,
 'air': 859,
 'iraq': 3668,
 'afghanistan': 824,
 'stable': 6359,
 'honest': 3416,
 'traveling': 6951,
 'mm': 4456,
 'feeling': 2752,
 'sleepy': 6152,
 'itself': 3693,
 'shall': 5985,
 'dear': 2148,
 'emigrated': 2531,
 'maybe': 4329,
 'hopeful': 3430,
 'gd': 3048,
 'shopping': 6038,
 'watch': 7319,
 'infernal': 3607,
 'affairs': 819,
 'lar': 3942,
 'tired': 6837,
 'arguing': 1036,
 'after': 829,
 'friend': 2955,
 '000': 1,
 'xmas': 7579,
 '08718726978': 133,
 'size': 6128,
 'elephant': 2514,
 'tablets': 6606,
 'shove': 6054,
 'um': 7051,
 'ass': 1084,
 'very': 7198,
 'happy': 3274,
 'woo': 7513,
 'hoo': 3423,
 'party': 5018,
 'king': 3867,
 'hill': 3370,
 'horrible': 3440,
 'macs': 4227,
 'until': 7107,
 'forgot': 2899,
 'abt': 747,
 'rite': 5721,
 'toot': 6903,
 'than': 6725,
 'b4': 1159,
 'prepared': 5310,
 'painful': 4978,
 'personal': 5092,
 'always': 912,
 'try': 6982,
 'everybody': 2621,
 'nobody': 4719,
 'recognises': 5570,
 'alone': 899,
 'asked': 1076,
 'anand': 939,
 'goodmorning': 3139,
 'howz': 3464,
 'pain': 4977,
 'ystrday': 7655,
 'ice': 3519,
 'medicine': 4350,
 'shit': 6022,
 'surprised': 6562,
 'went': 7383,
 'evening': 2615,
 'french': 2946,
 'guy': 3227,
 'met': 4392,
 'town': 6925,
 'fooled': 2882,
 'secure': 5907,
 'lemme': 3999,
 'drive': 2405,
 'south': 6275,
 'chill': 1744,
 'cool': 1961,
 'gentleman': 3062,
 'dignity': 2268,
 'respect': 5664,
 'eatin': 2467,
 'mountain': 4522,
 'deer': 2172,
 'show': 6056,
 'huh': 3479,
 'liao': 4017,
 'hi': 3362,
 'rd': 5519,
 'voucher': 7249,
 'holder': 3405,
 'weeks': 7366,
 'pc': 5051,
 'tlp': 6850,
 'reward': 5695,
 'ts': 6985,
 'apply': 1003,
 'double': 2369,
 'mins': 4424,
 'best': 1296,
 'orange': 4900,
 'tariffs': 6636,
 'latest': 3953,
 'camera': 1587,
 'phones': 5118,
 'mobileupd8': 4472,
 '08000839402': 45,
 '2stoptxt': 403,
 'khelate': 3851,
 'kintu': 3869,
 'opponenter': 4887,
 'dhorte': 2241,
 'lage': 3920,
 'rule': 5772,
 'receiving': 5561,
 'quality': 5452,
 'wins': 7463,
 'nothing': 4757,
 'still': 6411,
 'checked': 1713,
 'angry': 946,
 'misbehaved': 4431,
 'slap': 6145,
 'urself': 7140,
 'basically': 1216,
 '07732584351': 24,
 'rodger': 5734,
 'burns': 1528,
 'sms': 6191,
 'delivery': 2187,
 'wn': 7495,
 'prsn': 5405,
 'fight': 2781,
 'wit': 7476,
 'dem': 2189,
 'somtimes': 6243,
 'dis': 2284,
 'saves': 5848,
 'relation': 5605,
 'being': 1279,
 'quiet': 5463,
 'nothin': 4756,
 'eveb': 2613,
 'training': 6936,
 'darlin': 2119,
 'youphone': 7641,
 'athome': 1100,
 'youwanna': 7649,
 'chat': 1703,
 'meant': 4343,
 'calculation': 1564,
 'units': 7089,
 'school': 5865,
 'expensive': 2663,
 'started': 6378,
 'practicing': 5286,
 'accent': 755,
 'important': 3566,
 '4years': 519,
 'dental': 2196,
 'nmde': 4715,
 'exam': 2642,
 'yellow': 7615,
 'frndship': 2966,
 'misscall': 4436,
 'frndz': 2968,
 'see': 5910,
 'many': 4277,
 'calls': 1582,
 '6missed': 587,
 'marry': 4295,
 'lover': 4159,
 'diet': 2259,
 'ate': 1098,
 'slices': 6155,
 'pizza': 5154,
 'ugh': 7040,
 'blake': 1346,
 'able': 739,
 'little': 4076,
 'awesome': 1151,
 'restocked': 5675,
 'class': 1786,
 'takes': 6618,
 'shower': 6058,
 'dead': 2144,
 'yet': 7623,
 'god': 3118,
 'found': 2915,
 'glad': 3102,
 'xafter': 7573,
 'cst': 2049,
 'std': 6394,
 'ntwk': 4775,
 'chg': 1732,
 '50': 520,
 'had': 3238,
 '11': 256,
 'months': 4505,
 'entitled': 2569,
 'update': 7114,
 'mobiles': 4470,
 '08002986030': 50,
 'brother': 1489,
 'alert': 877,
 'computer': 1898,
 '10k': 252,
 'cash': 1634,
 '09064018838': 202,
 'ntt': 4774,
 'po': 5193,
 'box': 1421,
 'cro1327': 2034,
 'cost': 1977,
 '150ppm': 292,
 'vary': 7179,
 'baby': 1168,
 'nasty': 4623,
 'filthyguys': 2796,
 'rude': 5768,
 'bitch': 1337,
 'slo': 6162,
 'xxx': 7586,
 '4msgs': 506,
 'birthday': 1334,
 'electricity': 2513,
 'fml': 2863,
 'carlos': 1624,
 'tea': 6657,
 'which': 7416,
 'flavour': 2837,
 'pray': 5295,
 'ideas': 3528,
 'guys': 3228,
 'forward': 2912,
 'living': 4082,
 'simple': 6098,
 'loving': 4163,
 'laughing': 3958,
 'winning': 7462,
 'tooo': 6902,
 'difficult': 2263,
 'nte': 4772,
 'jus': 3800,
 'testing': 6708,
 'dunno': 2439,
 'network': 4670,
 'waiting': 7277,
 'sis': 6116,
 'bathing': 1223,
 'bathe': 1222,
 'dun': 2437,
 'disturb': 2306,
 'cleaning': 1793,
 'finished': 2806,
 'opinion': 4885,
 'jada': 3709,
 'kusruthi': 3902,
 'lovable': 4153,
 'silent': 6092,
 'spl': 6319,
 'character': 1692,
 'matured': 4321,
 'stylish': 6483,
 'dom': 2349,
 'told': 6874,
 'his': 3379,
 'name': 4609,
 'roger': 5736,
 'touch': 6919,
 'wants': 7304,
 'pm': 5191,
 'congrats': 1920,
 'kano': 3821,
 'whr': 7429,
 'maga': 4237,
 'yeah': 7609,
 'case': 1633,
 'scenario': 5861,
 'lesson': 4008,
 'lei': 3997,
 ...}

In [24]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7679,))

In [25]:
np.where(X_train_np[0]!=0)

(array([1027, 5339, 5971, 6210, 6728, 7636]),)

#### **Naive Bayes Classifier**

In [26]:
model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [27]:
y_pred = model.predict(X_test_cv)

In [28]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       955
           1       0.97      0.94      0.96       160

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115

#### **Test on a random datapoint**

In [29]:
message = {"Upto 20% off on parking, exclusing offer just for you"}

In [30]:
message_cnt = v.transform(message)

model.predict(message_cnt)

array([1])