In [5]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.datasets import fetch_california_housing
from sklearn.metrics import r2_score

In [6]:
california = fetch_california_housing()
data = pd.DataFrame(california.data, columns=california.feature_names)
target = pd.DataFrame(california.target, columns=['Price'])
df = pd.concat([data, target], axis=1)

In [7]:
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [8]:
df=pd.read_csv('boston.csv')
df.head()

,Unnamed: 0,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Price
0,0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2

In [9]:
#split the data into features and target

x = df.drop('Price',axis=1)
y = df['Price']

In [10]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  506 non-null    int64
 1   CRIM        506 non-null    float64
 2   ZN          506 non-null    float64
 3   INDUS       506 non-null    float64
 4   CHAS        506 non-null    float64
 5   NOX         506 non-null    float64
 6   RM          506 non-null    float64
 7   AGE         506 non-null    float64
 8   DIS         506 non-null    float64
 9   RAD         506 non-null    float64
 10  TAX         506 non-null    float64
 11  PTRATIO     506 non-null    float64
 12  B           506 non-null    float64
 13  LSTAT       506 non-null    float64
dtypes: float64(13), int64(1)
memory usage: 55.5 KB

In [11]:
x.head()

,Unnamed: 0,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33

In [12]:
y.info()

<class 'pandas.core.series.Series'>
RangeIndex: 506 entries, 0 to 505
Series name: Price
Non-Null Count  Dtype
--------------  -----
506 non-null    float64
dtypes: float64(1)
memory usage: 4.1 KB

In [13]:
y.head()

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: Price, dtype: float64

In [14]:
#split the data into train and test

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [15]:
len(x_train)

404

In [16]:
len(x_test)

102

Linear Regression

In [17]:
#applying the linear regression

model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [28]:
#calculate the r2score 

y_pred = model.predict(x_test)
r2_model = r2_score(y_test, y_pred)
print('R2 score of the model is:',r2_model)

R2 score of the model is: 0.5914577039362061

Ridge and Lasso Regression

In [29]:
from sklearn.linear_model import Ridge, Lasso

In [30]:
#applying the ridge regression

ridge_model = Ridge(alpha=1.0) # ridge cost function formula : (y-y hat) + lambda (slope)^2 . so lambda is 1.0 here. i am assuming this value it should be anything. 
ridge_model.fit(x_train, y_train)
y_pred_ridge = ridge_model.predict(x_test)
r2_model_ridge = r2_score(y_test, y_pred_ridge)
print('R2 score of the ridge model with alpha is:',r2_model_ridge)

R2 score of theridge model with alpha is: 0.5821546486185083

In [31]:
#applying the lasso regression

lasso_model = Lasso(alpha=1.0) # ridge cost function formula : (y-y hat) + lambda (slope)^2 . so lambda is 1.0 here. i am assuming this value it should be anything. 
lasso_model.fit(x_train, y_train)
y_pred_lasso = lasso_model.predict(x_test)
r2_model_lasso = r2_score(y_test, y_pred_lasso)
print('R2 score of the lasso model with alpha is:',r2_model_lasso)

R2 score of theridge model with alpha is: 0.485553580000618

In [32]:
df.head()

,Unnamed: 0,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Price
0,0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2

In [37]:
 df1 = df.iloc[:,1:] #delete the first column of the table df1 = df.drop(df.columns[0], axis=1)

In [38]:
df1

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Price
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,11.9

In [48]:
#identigy the coefficient with bad slope results
bad_features = np.where(lasso_model.coef_ == 0 )[0]
print('Features with bad slope reults: ', list(x.columns[bad_features]))

Features with bad slope reults:  ['INDUS', 'CHAS', 'NOX']

In [49]:
#remove these features
x_train_filtered = x_train.drop(x_train.columns[bad_features],axis=1)
x_train_filtered

,Unnamed: 0,CRIM,ZN,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
220,220,0.35809,0.0,6.951,88.5,2.8617,8.0,307.0,17.4,391.70,9.71
71,71,0.15876,0.0,5.961,17.5,5.2873,4.0,305.0,19.2,376.94,9.88
240,240,0.11329,30.0,6.897,54.3,6.3361,6.0,300.0,16.6,391.25,11.38
6,6,0.08829,12.5,6.012,66.6,5.5605,5.0,311.0,15.2,395.60,12.43
417,417,25.94060,0.0,5.304,89.1,1.6475,24.0,666.0,20.2,127.36,26.64
...,...,...,...,...,...,...,...,...,...,...,...
323,323,0.28392,0.0,5.708,74.3,4.7211,5.0,287.0,19.6,391.13,11.74
192,192,0.08664,45.0,7.178,26.3,6.4798,5.0,398.0,15.2,390.49,2.87
117,117,0.15098,0.0,6.021,82.6,2.7474,6.0,432.0,17.8,394.51,10.30
47,47,0.22927,0.0,6.030,85.5,5.6894,3.0,233.0,17.9,392.74,18.80
172,172,0.13914,0.0,5.572,88.5,2.5961,5.0,296.0,16.6,396.90,14.69

In [51]:
x_train_filtered1 = x_train_filtered.iloc[:,1:]
x_train_filtered1

         CRIM    ZN     RM   AGE     DIS   RAD    TAX  PTRATIO       B  LSTAT
220   0.35809   0.0  6.951  88.5  2.8617   8.0  307.0     17.4  391.70   9.71
71    0.15876   0.0  5.961  17.5  5.2873   4.0  305.0     19.2  376.94   9.88
240   0.11329  30.0  6.897  54.3  6.3361   6.0  300.0     16.6  391.25  11.38
6     0.08829  12.5  6.012  66.6  5.5605   5.0  311.0     15.2  395.60  12.43
417  25.94060   0.0  5.304  89.1  1.6475  24.0  666.0     20.2  127.36  26.64
..        ...   ...    ...   ...     ...   ...    ...      ...     ...    ...
323   0.28392   0.0  5.708  74.3  4.7211   5.0  287.0     19.6  391.13  11.74
192   0.08664  45.0  7.178  26.3  6.4798   5.0  398.0     15.2  390.49   2.87
117   0.15098   0.0  6.021  82.6  2.7474   6.0  432.0     17.8  394.51  10.30
47    0.22927   0.0  6.030  85.5  5.6894   3.0  233.0     17.9  392.74  18.80
172   0.13914   0.0  5.572  88.5  2.5961   5.0  296.0     16.6  396.90  14.69

[404 rows x 10 columns]

In [54]:
x_test_filtered = x_test.drop(x_test.columns[bad_features],axis=1)
x_test_filtered
x_test_filtered1 = x_test_filtered.iloc[:,1:]
x_test_filtered1

         CRIM    ZN     RM    AGE     DIS   RAD    TAX  PTRATIO       B  LSTAT
329   0.06724   0.0  6.333   17.2  5.2146   4.0  430.0     16.9  375.21   7.34
371   9.23230   0.0  6.216  100.0  1.1691  24.0  666.0     20.2  366.15   9.53
219   0.11425   0.0  6.373   92.4  3.3633   5.0  276.0     16.4  393.74  10.50
403  24.80170   0.0  5.349   96.0  1.7028  24.0  666.0     20.2  396.90  19.77
78    0.05646   0.0  6.232   53.7  5.0141   5.0  398.0     18.7  386.40  12.34
..        ...   ...    ...    ...     ...   ...    ...      ...     ...    ...
56    0.02055  85.0  6.383   35.7  9.1876   2.0  313.0     17.3  396.90   5.77
455   4.75237   0.0  6.525   86.5  2.4358  24.0  666.0     20.2   50.92  18.13
60    0.14932  25.0  5.741   66.2  7.2254   8.0  284.0     19.7  395.11  13.15
213   0.14052   0.0  6.375   32.3  3.9454   4.0  277.0     18.6  385.81   9.38
108   0.12802   0.0  6.474   97.1  2.4329   5.0  384.0     20.9  395.24  12.27

[102 rows x 10 columns]

In [59]:
#applying the linear regression and lasso regression on filtered data

model_filtered_lr = LinearRegression()
model_filtered_lr.fit(x_train_filtered1, y_train)

model_filtered_lasso = Lasso(alpha=1.0)
model_filtered_lasso.fit(x_train_filtered1, y_train)

y_pred_lrfiltered = model_filtered_lr.predict(x_test_filtered1)
r2_model_lrfiltered = r2_score(y_test, y_pred_lrfiltered)
print('R2 score of the linear regression model is', r2_model_lrfiltered)

y_pred_lassofiltered = model_filtered_lasso.predict(x_test_filtered1)
r2_model_lassofiltered = r2_score(y_test, y_pred_lassofiltered)
print('R2 score of the lasso model with alpha 1.0 is', r2_model_lassofiltered)

R2 score of the linear regression model is 0.5558354547335733
R2 score of the lasso model with alpha 1.0 is 0.48789074983581004